name: Build Extension
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Build Package
        run: bash build-extension.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-build
          path: dist/*.zip
