name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: mbologna/.github/.github/workflows/tag-release.yml@bc67bfd693eafaf8371ae6ba2626e1f977ab3311
    with:
      node_version: '18'
      build_command: chmod +x build-extension.sh && ./build-extension.sh
    permissions:
      contents: write
